/**
 * Common “endo fodder” rares players rack up while casually playing —
 * vault corrupted, nightmare, staple loot rares, and open-world set mods.
 * Not augments, primed, or galvanized (intentional farms / `/syndicates`).
 *
 * Names match warframe.market via normalizeModName.
 */

import { normalizeModName } from "./syndicates";

export const FODDER_MODS: readonly string[] = [
  // Corrupted (Orokin Vault)
  "Blind Rage",
  "Transient Fortitude",
  "Fleeting Expertise",
  "Overextended",
  "Narrow Minded",
  "Heavy Caliber",
  "Catalyzing Shields",
  "Critical Delay",
  "Vile Acceleration",
  "Vile Precision",
  "Vicious Spread",
  "Tainted Clip",
  "Magnum Force",
  "Hollow Point",
  "Creeping Bullseye",
  "Spoiled Strike",
  "Corrupt Charge",
  "Depleted Reload",
  "Burdened Magazine",
  "Critical Deceleration",

  // Nightmare
  "Constitution",
  "Fortitude",
  "Animal Instinct",
  "Lethal Torrent",
  "Wildfire",
  "Ice Storm",
  "Shred",
  "Seeking Fury",
  "Accelerated Blast",
  "Hammer Shot",
  "Stunning Speed",
  "Focus Energy",
  "Ravage",
  "Streamlined Form",
  "Armored Agility",

  // Staple warframe rares
  "Intensify",
  "Continuity",
  "Flow",
  "Stretch",
  "Streamline",
  "Rage",
  "Equilibrium",
  "Natural Talent",
  "Quick Thinking",
  "Enemy Radar",
  "Thief's Wit",
  "Master Thief",
  "Reflection",
  "Handspring",
  "Sure Footed",
  "Pain Threshold",
  "Undying Will",
  "Vital Sense",
  "Redirection",
  "Vitality",
  "Steel Fiber",
  "Fast Deflection",
  "Vigor",

  // Staple weapon rares
  "Serration",
  "Split Chamber",
  "Point Blank",
  "Hell's Chamber",
  "Hornet Strike",
  "Barrel Diffusion",
  "Pressure Point",
  "True Steel",
  "Organ Shatter",
  "Life Strike",
  "Killing Blow",
  "Fury",
  "Reach",
  "Stormbringer",
  "Infected Clip",
  "Hellfire",
  "Cryo Rounds",
  "Deep Freeze",
  "Heated Charge",
  "Pathogen Rounds",
  "Convulsion",
  "Pistol Pestilence",
  "Jolt",
  "Frostbite",
  "Scorch",
  "High Voltage",
  "Malignant Force",
  "Rime Rounds",
  "Thermite Rounds",
  "Shell Shock",
  "Frigid Blast",
  "Toxic Barrage",
  "Sweeping Serration",
  "Virulent Scourge",
  "Volcanic Edge",
  "Voltaic Strike",
  "Vicious Frost",

  // Open-world / bounty set rares
  "Augur Secrets",
  "Augur Message",
  "Augur Reach",
  "Augur Accord",
  "Augur Pact",
  "Augur Seeker",
  "Vigilante Supplies",
  "Vigilante Armaments",
  "Vigilante Fervor",
  "Vigilante Offense",
  "Vigilante Pursuit",
  "Vigilante Vigor",
  "Gladiator Aegis",
  "Gladiator Finesse",
  "Gladiator Resolve",
  "Gladiator Might",
  "Gladiator Rush",
  "Gladiator Vice",
  "Hunter Adrenaline",
  "Hunter Recovery",
  "Hunter Synergy",
  "Hunter Track",
  "Hunter Munitions",
  "Hunter Command",
  "Motus Signal",
  "Motus Impact",
  "Motus Setup",
  "Proton Pulse",
  "Proton Jet",
  "Proton Snap",
  "Tek Assault",
  "Tek Collateral",
  "Tek Enhance",
  "Tek Gravity",
  "Mecha Empowered",
  "Mecha Overdrive",
  "Mecha Pulse",
  "Mecha Reinforced",
  "Synth Charge",
  "Synth Deconstruct",
  "Synth Fiber",
  "Synth Reflex",
  "Strain Consume",
  "Strain Fever",
  "Strain Infection",
  "Strain Eruption",
  "Cunning Drift",
  "Power Drift",
  "Speed Drift",
  "Endurance Drift",
];

const fodderLookup = new Set(FODDER_MODS.map((name) => normalizeModName(name)));

export function isFodderMod(itemName: string): boolean {
  return fodderLookup.has(normalizeModName(itemName));
}
