/**
 * Syndicate augment mod catalog for the 6 base syndicates.
 *
 * Sourced from the Warframe wiki syndicate offering pages (25,000-standing
 * mods: rank 5 warframe augments + rank 4 weapon augments) — the WFCD
 * warframe-items drop data proved stale/vendor-polluted (e.g. Nezha's
 * Safeguard listed under four syndicates). Names match warframe.market item
 * names case-insensitively (see normalizeModName).
 *
 * When DE adds new syndicate augments, regenerate or append entries here.
 * v2 item tags are stored on items.tags as future auto-detection input.
 */

export const SYNDICATES = [
  "Steel Meridian",
  "Arbiters of Hexis",
  "Cephalon Suda",
  "The Perrin Sequence",
  "Red Veil",
  "New Loka",
] as const;

export type SyndicateName = (typeof SYNDICATES)[number];

export interface SyndicateModEntry {
  name: string;
  /** Warframe or weapon the mod is for, when known. */
  compat: string | null;
  /** Indexes into SYNDICATES — most augments are sold by two syndicates. */
  syndicates: number[];
}

/** Lowercases and strips non-alphanumerics so dataset names match WFM item names. */
export function normalizeModName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

/** URL-safe slug for a syndicate name, e.g. "The Perrin Sequence" → "the_perrin_sequence". */
export function syndicateSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
}

export const SYNDICATE_MODS: SyndicateModEntry[] = [
{ name: "Abating Link", compat: "Trinity", syndicates: [3, 5] },
  { name: "Abundant Mutation", compat: "Nidus", syndicates: [0, 3] },
  { name: "Accumulating Whipclaw", compat: "Khora", syndicates: [0, 4] },
  { name: "Afterburn", compat: "Chroma", syndicates: [2, 3] },
  { name: "Airburst Rounds", compat: "Zephyr", syndicates: [4, 5] },
  { name: "Anchored Glide", compat: "Zephyr", syndicates: [4, 5] },
  { name: "Antimatter Absorb", compat: "Nova", syndicates: [0, 2] },
  { name: "Assimilate", compat: "Nyx", syndicates: [1, 5] },
  { name: "Avenging Truth", compat: "Silva & Aegis", syndicates: [1] },
  { name: "Axios Javelineers", compat: "Styanax", syndicates: [1, 5] },
  { name: "Balefire Surge", compat: "Hildryn", syndicates: [2, 3] },
  { name: "Ballistic Bullseye", compat: "Mesa", syndicates: [0, 4] },
  { name: "Beguiling Lantern", compat: "Titania", syndicates: [4, 5] },
  { name: "Biting Frost", compat: "Frost", syndicates: [0, 2] },
  { name: "Blade of Truth", compat: "Jaw Sword", syndicates: [1] },
  { name: "Blazing Pillage", compat: "Hildryn", syndicates: [2, 3] },
  { name: "Blending Talons", compat: "Garuda", syndicates: [0, 4] },
  { name: "Blinding Reave", compat: "Revenant", syndicates: [2, 3] },
  { name: "Blood Forge", compat: "Garuda", syndicates: [0, 4] },
  { name: "Bright Purity", compat: "Skana", syndicates: [5] },
  { name: "Calm & Frenzy", compat: "Equinox", syndicates: [1, 5] },
  { name: "Capacitance", compat: "Volt", syndicates: [1, 4] },
  { name: "Cataclysmic Continuum", compat: "Limbo", syndicates: [1, 2] },
  { name: "Catapult", compat: "Grendel", syndicates: [0, 4] },
  { name: "Cathode Current", compat: "Gyre", syndicates: [1, 3] },
  { name: "Celestial Stomp", compat: "Wukong", syndicates: [1, 5] },
  { name: "Champion's Blessing", compat: "Trinity", syndicates: [3, 5] },
  { name: "Chaos Sphere", compat: "Nyx", syndicates: [1, 5] },
  { name: "Chilling Globe", compat: "Frost", syndicates: [0, 2] },
  { name: "Chromatic Blade", compat: "Excalibur", syndicates: [0, 1] },
  { name: "Concentrated Arrow", compat: "Ivara", syndicates: [2, 3] },
  { name: "Conductor", compat: "Octavia", syndicates: [2, 5] },
  { name: "Contagion Cloud", compat: "Saryn", syndicates: [0, 4] },
  { name: "Controlled Slide", compat: "Nezha", syndicates: [0, 2] },
  { name: "Counter Pulse", compat: "Mag", syndicates: [3, 5] },
  { name: "Creeping Terrify", compat: "Nekros", syndicates: [3, 4] },
  { name: "Critical Surge", compat: "Wisp", syndicates: [2, 5] },
  { name: "Damage Decoy", compat: "Loki", syndicates: [1, 4] },
  { name: "Deadly Sequence", compat: "Grinlok", syndicates: [3] },
  { name: "Desiccation's Curse", compat: "Inaros", syndicates: [1, 3] },
  { name: "Despoil", compat: "Nekros", syndicates: [3, 4] },
  { name: "Disarming Purity", compat: "Panthera", syndicates: [5] },
  { name: "Divine Retribution", compat: "Nezha", syndicates: [0, 2] },
  { name: "Dread Ward", compat: "Garuda", syndicates: [0, 4] },
  { name: "Duality", compat: "Equinox", syndicates: [1, 5] },
  { name: "Elemental Sandstorm", compat: "Inaros", syndicates: [1, 3] },
  { name: "Elusive Retribution", compat: "Baruuk", syndicates: [1, 5] },
  { name: "Empowered Quiver", compat: "Ivara", syndicates: [2, 3] },
  { name: "Endless Lullaby", compat: "Baruuk", syndicates: [1, 5] },
  { name: "Energy Transfer", compat: "Equinox", syndicates: [1, 5] },
  { name: "Enraged", compat: "Valkyr", syndicates: [3, 5] },
  { name: "Entropy Burst", compat: "Supra", syndicates: [2] },
  { name: "Entropy Detonation", compat: "Obex", syndicates: [2] },
  { name: "Entropy Flight", compat: "Kestrel", syndicates: [2] },
  { name: "Entropy Spike", compat: "Bolto", syndicates: [2] },
  { name: "Enveloping Cloud", compat: "Wukong", syndicates: [1, 5] },
  { name: "Eroding Blight", compat: "Embolist", syndicates: [4] },
  { name: "Escape Velocity", compat: "Nova", syndicates: [0, 2] },
  { name: "Eternal War", compat: "Valkyr", syndicates: [3, 5] },
  { name: "Everlasting Ward", compat: "Chroma", syndicates: [2, 3] },
  { name: "Exothermic", compat: "Ember", syndicates: [0, 4] },
  { name: "Explosive Legerdemain", compat: "Mirage", syndicates: [1, 2] },
  { name: "Teleport Rush", compat: "Ash", syndicates: [1, 4] },
  { name: "Fireball Frenzy", compat: "Ember", syndicates: [0, 4] },
  { name: "Fracturing Crush", compat: "Mag", syndicates: [3, 5] },
  { name: "Freeze Force", compat: "Frost", syndicates: [0, 2] },
  { name: "Funnel Clouds", compat: "Zephyr", syndicates: [4, 5] },
  { name: "Furious Javelin", compat: "Excalibur", syndicates: [0, 1] },
  { name: "Fused Reservoir", compat: "Wisp", syndicates: [2, 5] },
  { name: "Gilded Truth", compat: "Burston Prime", syndicates: [1] },
  { name: "Gleaming Blight", compat: "Dark Dagger", syndicates: [4] },
  { name: "Gourmand", compat: "Grendel", syndicates: [0, 4] },
  { name: "Greedy Pull", compat: "Mag", syndicates: [3, 5] },
  { name: "Guardian Armor", compat: "Chroma", syndicates: [2, 3] },
  { name: "Guided Effigy", compat: "Chroma", syndicates: [2, 3] },
  { name: "Hall of Malevolence", compat: "Mirage", syndicates: [1, 2] },
  { name: "Hallowed Eruption", compat: "Oberon", syndicates: [0, 5] },
  { name: "Hallowed Reckoning", compat: "Oberon", syndicates: [0, 5] },
  { name: "Healing Flame", compat: "Ember", syndicates: [0, 4] },
  { name: "Hearty Nourishment", compat: "Grendel", syndicates: [0, 4] },
  { name: "Hushed Invisibility", compat: "Loki", syndicates: [1, 4] },
  { name: "Hysterical Assault", compat: "Valkyr", syndicates: [3, 5] },
  { name: "Ice Wave Impedance", compat: "Frost", syndicates: [0, 2] },
  { name: "Icy Avalanche", compat: "Frost", syndicates: [0, 2] },
  { name: "Immolated Radiance", compat: "Ember", syndicates: [0, 4] },
  { name: "Infiltrate", compat: "Ivara", syndicates: [2, 3] },
  { name: "Insatiable", compat: "Nidus", syndicates: [0, 3] },
  { name: "Intrepid Stand", compat: "Styanax", syndicates: [1, 5] },
  { name: "Iron Shrapnel", compat: "Rhino", syndicates: [0, 3] },
  { name: "Ironclad Charge", compat: "Rhino", syndicates: [0, 3] },
  { name: "Ironclad Flight", compat: "Titania", syndicates: [4, 5] },
  { name: "Irradiating Disarm", compat: "Loki", syndicates: [1, 4] },
  { name: "Jet Stream", compat: "Zephyr", syndicates: [4, 5] },
  { name: "Justice Blades", compat: "Dual Cleavers", syndicates: [0] },
  { name: "Larva Burst", compat: "Nidus", syndicates: [0, 3] },
  { name: "Lasting Covenant", compat: "Harrow", syndicates: [1, 4] },
  { name: "Lasting Purity", compat: "Vulkar", syndicates: [5] },
  { name: "Loyal Merulina", compat: "Yareli", syndicates: [2, 5] },
  { name: "Mach Crash", compat: "Gauss", syndicates: [1, 3] },
  { name: "Magnetized Discharge", compat: "Mag", syndicates: [3, 5] },
  { name: "Mending Splinters", compat: "Gara", syndicates: [1, 5] },
  { name: "Merulina Guardian", compat: "Yareli", syndicates: [2, 5] },
  { name: "Mesa's Waltz", compat: "Mesa", syndicates: [0, 4] },
  { name: "Mesmer Shield", compat: "Revenant", syndicates: [2, 3] },
  { name: "Mind Freak", compat: "Nyx", syndicates: [1, 5] },
  { name: "Molecular Fission", compat: "Nova", syndicates: [0, 2] },
  { name: "Muzzle Flash", compat: "Mesa", syndicates: [0, 4] },
  { name: "Negation Armor", compat: "Inaros", syndicates: [1, 3] },
  { name: "Neutralizing Justice", compat: "Miter", syndicates: [0] },
  { name: "Neutron Star", compat: "Nova", syndicates: [0, 2] },
  { name: "Ore Gaze", compat: "Atlas", syndicates: [0, 4] },
  { name: "Pacifying Bolts", compat: "Nyx", syndicates: [1, 5] },
  { name: "Parasitic Vitality", compat: "Nidus", syndicates: [0, 3] },
  { name: "Partitioned Mallet", compat: "Octavia", syndicates: [2, 5] },
  { name: "Path of Statues", compat: "Atlas", syndicates: [0, 4] },
  { name: "Peaceful Provocation", compat: "Equinox", syndicates: [1, 5] },
  { name: "Phoenix Renewal", compat: "Oberon", syndicates: [0, 5] },
  { name: "Photon Repeater", compat: "Vauban", syndicates: [2, 3] },
  { name: "Piercing Navigator", compat: "Ivara", syndicates: [2, 3] },
  { name: "Piercing Roar", compat: "Rhino", syndicates: [0, 3] },
  { name: "Pilfering Strangledome", compat: "Khora", syndicates: [0, 4] },
  { name: "Pilfering Swarm", compat: "Hydroid", syndicates: [2, 5] },
  { name: "Pool Of Life", compat: "Trinity", syndicates: [3, 5] },
  { name: "Primal Rage", compat: "Wukong", syndicates: [1, 5] },
  { name: "Prolonged Paralysis", compat: "Valkyr", syndicates: [3, 5] },
  { name: "Pyroclastic Flow", compat: "Nezha", syndicates: [0, 2] },
  { name: "Radiant Finish", compat: "Excalibur", syndicates: [0, 1] },
  { name: "Razorwing Blitz", compat: "Titania", syndicates: [4, 5] },
  { name: "Reactive Storm", compat: "Baruuk", syndicates: [1, 5] },
  { name: "Reaping Chakram", compat: "Nezha", syndicates: [0, 2] },
  { name: "Recrystalize", compat: "Citrine", syndicates: [0, 4] },
  { name: "Regenerative Molt", compat: "Saryn", syndicates: [0, 4] },
  { name: "Reinforcing Stomp", compat: "Rhino", syndicates: [0, 3] },
  { name: "Repair Dispensary", compat: "Protea", syndicates: [1, 3] },
  { name: "Enduring Bastille", compat: "Vauban", syndicates: [2, 3] },
  { name: "Resonance", compat: "Banshee", syndicates: [2, 3] },
  { name: "Resonating Quake", compat: "Banshee", syndicates: [2, 3] },
  { name: "Revealing Spores", compat: "Saryn", syndicates: [0, 4] },
  { name: "Rift Haven", compat: "Limbo", syndicates: [1, 2] },
  { name: "Rift Torrent", compat: "Limbo", syndicates: [1, 2] },
  { name: "Rising Storm", compat: "Ash", syndicates: [1, 4] },
  { name: "Rousing Plunder", compat: "Hydroid", syndicates: [2, 5] },
  { name: "Rubble Heap", compat: "Atlas", syndicates: [0, 4] },
  { name: "Safeguard", compat: "Nezha", syndicates: [0, 2] },
  { name: "Safeguard Switch", compat: "Loki", syndicates: [1, 4] },
  { name: "Savage Silence", compat: "Banshee", syndicates: [2, 3] },
  { name: "Savior Decoy", compat: "Loki", syndicates: [1, 4] },
  { name: "Scattered Justice", compat: "Hek", syndicates: [0] },
  { name: "Seeking Shuriken", compat: "Ash", syndicates: [1, 4] },
  { name: "Sequence Burn", compat: "Spectra", syndicates: [3] },
  { name: "Shadow Haze", compat: "Sevagoth", syndicates: [2, 3] },
  { name: "Shattered Storm", compat: "Gara", syndicates: [1, 5] },
  { name: "Shattering Justice", compat: "Sobek", syndicates: [0] },
  { name: "Shield of Shadows", compat: "Nekros", syndicates: [3, 4] },
  { name: "Shock Trooper", compat: "Volt", syndicates: [1, 4] },
  { name: "Shocking Speed", compat: "Volt", syndicates: [1, 4] },
  { name: "Smite Infusion", compat: "Oberon", syndicates: [0, 5] },
  { name: "Smoke Shadow", compat: "Ash", syndicates: [1, 4] },
  { name: "Sonic Fracture", compat: "Banshee", syndicates: [2, 3] },
  { name: "Soul Survivor", compat: "Nekros", syndicates: [3, 4] },
  { name: "Spectrosiphon", compat: "Gara", syndicates: [1, 5] },
  { name: "Spellbound Harvest", compat: "Titania", syndicates: [4, 5] },
  { name: "Staggering Shield", compat: "Mesa", syndicates: [0, 4] },
  { name: "Stinging Truth", compat: "Viper", syndicates: [1] },
  { name: "Stockpiled Blight", compat: "Kunai", syndicates: [4] },
  { name: "Surging Blades", compat: "Yareli", syndicates: [2, 5] },
  { name: "Surging Dash", compat: "Excalibur", syndicates: [0, 1] },
  { name: "Swift Bite", compat: "Lavos", syndicates: [4, 5] },
  { name: "Swing Line", compat: "Valkyr", syndicates: [3, 5] },
  { name: "Target Fixation", compat: "Zephyr", syndicates: [4, 5] },
  { name: "Tectonic Fracture", compat: "Atlas", syndicates: [0, 4] },
  { name: "Teeming Virulence", compat: "Nidus", syndicates: [0, 3] },
  { name: "Temporal Erosion", compat: "Protea", syndicates: [1, 3] },
  { name: "Tesla Bank", compat: "Vauban", syndicates: [2, 3] },
  { name: "The Relentless Lost", compat: "Xaku", syndicates: [0, 2] },
  { name: "Thermal Transfer", compat: "Gauss", syndicates: [1, 3] },
  { name: "Thrall Pact", compat: "Revenant", syndicates: [2, 3] },
  { name: "Tidal Impunity", compat: "Hydroid", syndicates: [2, 5] },
  { name: "Titanic Rumbler", compat: "Atlas", syndicates: [0, 4] },
  { name: "Total Eclipse", compat: "Mirage", syndicates: [1, 2] },
  { name: "Toxic Blight", compat: "Mire", syndicates: [4] },
  { name: "Toxic Sequence", compat: "Acrid", syndicates: [3] },
  { name: "Transistor Shield", compat: "Volt", syndicates: [1, 4] },
  { name: "Tribunal", compat: "Harrow", syndicates: [1, 4] },
  { name: "Ulfrun's Endurance", compat: "Voruna", syndicates: [0, 4] },
  { name: "Valence Formation", compat: "Lavos", syndicates: [4, 5] },
  { name: "Vampire Leech", compat: "Trinity", syndicates: [3, 5] },
  { name: "Vampiric Grasp", compat: "Xaku", syndicates: [0, 2] },
  { name: "Venari Bodyguard", compat: "Khora", syndicates: [0, 4] },
  { name: "Venom Dose", compat: "Saryn", syndicates: [0, 4] },
  { name: "Vexing Retaliation", compat: "Chroma", syndicates: [2, 3] },
  { name: "Viral Tempest", compat: "Hydroid", syndicates: [2, 5] },
  { name: "Voltage Sequence", compat: "Lanka", syndicates: [3] },
  { name: "Warding Thurible", compat: "Harrow", syndicates: [1, 4] },
  { name: "Warrior's Rest", compat: "Excalibur Umbra", syndicates: [1, 4] },
  { name: "Winds of Purity", compat: "Furis", syndicates: [5] },
  { name: "Wrath of Ukko", compat: "Kullervo", syndicates: [0, 5] },
];

const modLookup = new Map<string, SyndicateModEntry>(
  SYNDICATE_MODS.map((entry) => [normalizeModName(entry.name), entry]),
);

/** Returns the syndicate mod entry for a WFM item name, or undefined. */
export function findSyndicateMod(itemName: string): SyndicateModEntry | undefined {
  return modLookup.get(normalizeModName(itemName));
}
